import { SITE } from "@/lib/seo/site";
import { getProfile, getProjectsMerged, getExperiences, getSkills, getFaqs } from "@/lib/queries";
import type { SkillRow } from "@/lib/queries";

export const dynamic = "force-static";

function groupSkills(skills: SkillRow[]): string {
  const groups = new Map<string, string[]>();
  for (const s of skills) groups.set(s.category, [...(groups.get(s.category) ?? []), s.name]);
  return [...groups]
    .map(([category, names]) => `### ${category}\n- ${names.join(", ")}`)
    .join("\n\n");
}

export async function GET() {
  // Same source as the homepage, so this file cannot drift from what the site shows.
  const profile = await getProfile();
  const show = (id: string) => profile.sectionVisibility[id] !== false;
  const [projects, experiences, skills, faqs] = await Promise.all([
    show("projects") ? getProjectsMerged() : Promise.resolve([]),
    show("experience") ? getExperiences() : Promise.resolve([]),
    show("skills") ? getSkills() : Promise.resolve([]),
    getFaqs(),
  ]);
  const current = experiences.find((e) => e.isCurrent);
  const { years, repos, stars, followers } = profile.stats;

  const body = `# ${SITE.name} - Full Profile

> ${SITE.description}

## Identity

- **Name:** ${profile.name}
- **Handle:** nixrajput
- **Role:** ${profile.roles.join(" · ")}
${current ? `- **Currently:** ${current.role} at ${current.org} (${current.period})\n` : ""}- **Based in:** India
- **Founder of:** NixLab - a personal software studio for open-source tools and products

## Bio

${profile.bio}

## By the numbers

- **Years of professional experience:** ${years}
- **Public repositories:** ${repos}
- **GitHub stars across owned repositories:** ${stars}
- **GitHub followers:** ${followers}

## Tech Stack

${groupSkills(skills)}

## Projects

${projects
  .map((p) => {
    const url = p.htmlUrl ?? `https://github.com/nixrajput/${p.repo}`;
    const stats = p.stars === null ? "" : ` (${p.stars} GitHub stars)`;
    const tags = p.tags.length ? ` Tags: ${p.tags.join(", ")}.` : "";
    return `- **${p.title}**${p.featured ? " (featured)" : ""} - ${p.description ?? ""}${stats} - ${url}.${tags}`;
  })
  .join("\n")}

## Experience

${experiences
  .map((e) => {
    const where = e.location ? `, ${e.location}` : "";
    const bullets = e.description.map((d) => `  - ${d}`).join("\n");
    return `- **${e.role}** - ${e.org}${where} · ${e.period}${bullets ? `\n${bullets}` : ""}`;
  })
  .join("\n")}

## Open-Source

GitHub: https://github.com/nixrajput

## Availability

Nikhil is open to:
- Open-source collaboration
- Freelance engagements
- Advisory roles

He is not actively job-seeking but welcomes conversations about interesting projects.

## FAQ

${faqs.map((f) => `### ${f.question}\n${f.answer}`).join("\n\n")}

## Contact

- Site: ${SITE.url}
- Email: via the Contact section at ${SITE.url}/#contact
${SITE.sameAs.map((u) => `- ${u}`).join("\n")}

---
Last updated: ${new Date().getFullYear()}
Generated by ${SITE.url}
`;

  return new Response(body, {
    headers: { "Content-Type": "text/plain; charset=utf-8" },
  });
}
